//IBMUSERC JOB 'CRTHFS',MSGCLASS=S,NOTIFY=&SYSUID,REGION=0M
//HFS  EXEC PGM=IEFBR14
//HFS01 DD DSN=&SYSUID..ISV.HFS,DSNTYPE=HFS,DCB=(DSORG=PO),SPACE=(CYL,
//        (20,20)),
//      VOL=SER=USER01,
//      DISP=(NEW,CATLG,DELETE)
